# No Training Settings

# Hyperparameter Settings
perform_hyperparameter_optimization: false 
use_baseline_hyperparameters: true # false = use current best hyperparameters

# Hyperparameter Optimization
optimizer: Optuna   #only Optuna is supported currently

static_params:
  random_state: 42
  n_jobs: -1
  verbose: 0

optimization:
  n_trials: 100
  param_space:
    n_estimators: [10, 1000, int]
    max_depth: [1, 20, int]
    min_samples_split: [2, 20, int]
    min_samples_leaf: [1, 10, int]
    max_features: [0.1, 1.0, float] 