# Data access configuration
newly_scraped_directory: data/newly_scraped/
cumulative_scraped_directory: data/cumulative_scraped/
processed_data_directory: data/processed/

# Scraped boxscore files
scraped_boxscore_files:
  - games_traditional.csv
  - games_advanced.csv
  - games_four-factors.csv
  - games_misc.csv
  - games_scoring.csv

# Today's matchups and game IDs files
todays_matchups_file: todays_matchups.csv
todays_games_ids_file: todays_games_ids.csv

# Processed data files
team_centric_data_file: teams_boxscores.csv # one row per team per game
game_centric_data_file: games_boxscores.csv # one row per game, both teams combined

# Column mapping file
column_mapping_file: column_mapping.json