# Web scraping configuration

# Game date spelled in different ways in each stat_type table
game_date_header_variations:
  - Game Date
  - Game_Date
  - GAME DATE
  - "Game\xa0Date"

# Scraping settings
full_scrape: false
start_season: 2006
off_season_start_month: 8
regular_season_start_month: 10
play_in_month: 4

# NBA URLs
nba_boxscores_url: https://www.nba.com/stats/teams/boxscores
nba_schedule_url: https://www.nba.com/schedule

# Season types
regular_season_text: Regular+Season
play_in_season_text: PlayIn
playoffs_season_text: Playoffs

# Stat types to scrape
stat_types:
  - traditional
  - advanced
  - four-factors
  - misc
  - scoring

# CSS class names for scraping
table_class_name: Crom_table__p1iZz
pagination_class_name: Pagination_pageDropdown__KgjBU
dropdown_class_name: DropDown_select__4pIg9
teams_and_games_class_name: Anchor_anchor__cSc3P
games_per_day_class_name: ScheduleDay_sdGames__NGdO5
day_class_name: ScheduleDay_sdDay__3s2Xt
teams_links_class_name: Anchor_anchor__cSc3P Link_styled__okbXW
game_links_class_name: Anchor_anchor__cSc3P TabLink_link__f_15h

# Timeout settings if page or dynamic content (tables) take too long to load
page_load_timeout: 30
dynamic_content_timeout: 30 

# Retry settings
max_retries: 2
retry_delay: 2
wait_time: 10


# Browser options (first is the default, second is the fallback)
browsers:
  - chrome
  - firefox

  # Chrome-specific options
chrome_options:
  --headless: "new"
  --no-sandbox: null
  --start-maximized: null
  --disable-dev-shm-usage: null
  --ignore-certificate-errors: null
  --ignore-ssl-errors: null
  --disable-gpu: null
  --disable-extensions: null
  --disable-popup-blocking: null
  --disable-notifications: null
  --remote-debugging-port: 9222
  --disable-3d-apis: null
  --disable-blink-features=AutomationControlled: null
  --user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"



# Firefox-specific options
firefox_options:
  --headless: null
  --disable-blink-features=AutomationControlled: null
  --user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"

