# Optuna optimization settings
optuna:
  scoring: auc
  direction: maximize
  pruner: 'median'  # Available: 'median', 'hyperband', 'threshold'
  n_startup_trials: 20
  n_warmup_steps: 5
  interval_steps: 1

