# Data access configuration
newly_scraped_directory: data/newly_scraped/
cumulative_scraped_directory: data/cumulative_scraped/
processed_data_directory: data/processed/
engineered_data_directory: data/engineered/
training_data_directory: data/training/
evaluation_data_directory: data/evaluation/

# Scraped boxscore files
scraped_boxscore_files:
  - games_traditional.csv
  - games_advanced.csv
  - games_four-factors.csv
  - games_misc.csv
  - games_scoring.csv

# Today's matchups and game IDs files
todays_matchups_file: todays_matchups.csv
todays_games_ids_file: todays_games_ids.csv

# Processed data files
team_centric_data_file: teams_boxscores.csv # one row per team per game
game_centric_data_file: games_boxscores.csv # one row per game, both teams combined

# Engineered data files
engineered_data_file: engineered_features.csv

# Column mapping file
column_mapping_file: column_mapping.json

# Training data files
training_data_file: training_data.csv
validation_data_file: validation_data.csv
evaluation_data_file: evaluation_data.csv
