# settings for experiment logging
experiment_name: "NBA Predictor"
experiment_description: "NBA Predictor"
tracking_uri: None


#sort columns - ensures that the columns are in the correct order - important for TimeSeriesSplit cross validation
sort_columns:
  - season
  - season_progress

# sort order: ascending = true, descending = false
sort_order:
  - true
  - true

# primary id for the dataframe - not used for modeling, but useful for analyzing predictions
primary_id_column: game_id

# these columns are not useful for modeling - just informational text that is already encoded elsewhere
# they will be dropped from the dataframe right before modeling
non_useful_columns: 
  #-

# indicates which columns are categorical so they can be encoded and identified by the model
categorical_features:
  - h_team_id
  - v_team_id

# this allows you to skip preprocessing for all models without having to disable all the settings in the preprocessing_config.yaml file
# the individual settings are in the preprocessing_config.yaml file
perform_preprocessing: false

# hyperparameters path (${PROJECT_ROOT} is the root directory of the project and is parsed from the environment variable in config.py)
current_hyperparameters: "${PROJECT_ROOT}/configs/hyperparameters.json"

# hyperparameters storage directory
hyperparameter_history_dir: "${PROJECT_ROOT}/hyperparameter_history"

# hyperparameter metadata - fields that are not used as hyperparameters but may be included in tracking
hyperparameter_metadata:
  - name
  - metrics
  - updated_at
  - experiment_id
  - run_id
  - num_boost_round
  - early_stopping
  - enable_categorical
  - categorical_features


# model testing options
perform_oof_cross_validation: true
perform_validation_set_testing: true
save_oof_predictions: false # save the predictions for the out of fold cross validation to a csv file
save_validation_predictions: true # save the predictions for the validation set to a csv file
log_experiment: true


# Cross validation settings (only TimeSeriesSplit or StratifiedKFold are supported currently)
cross_validation_type: TimeSeriesSplit
n_splits: 5
random_state: 42

# models to use in this experiment run
models:
  xgboost: true
  lgbm: false
  catboost: false
  sklearn:
    random_forest: false
    logistic_regression: false
    hist_gradient_boosting: false


# learning curve settings
generate_learning_curve_data: true 

# SHAP settings
calculate_shap_values: true
max_shap_interaction_memory_gb: 256.0
calculate_shap_interactions: false






