#sort columns
sort_columns:
  - season
  - season_progress

# sort order: ascending = true, descending = false
sort_order:
  - true
  - true

# model testing options
perform_oof_cross_validation: true
perform_validation_set_testing: true
save_oof_predictions: true # save the predictions for the out of fold cross validation to a csv file
save_validation_predictions: true # save the predictions for the validation set to a csv file
log_experiment: true

# primary id for the dataframe - not used for modeling, but useful for analyzing predictions
primary_id_column: game_id

# these columns are not useful for modeling - just informational text that is already encoded elsewhere
# they will be dropped from the dataframe right before modeling
non_useful_columns: 
  #-

# indicates which columns are categorical so they can be encoded and identified by the model
categorical_features:
  - h_team_id
  - v_team_id
 
# random state for cross validation and model training
random_state: 42

# set to "Default" to use a timestamp for the experiment name
experiment_name: "NBA Predictor"

# set to "Default" to use a timestamp for the experiment description
experiment_description: "NBA Predictor"

# models
models:
  #- XGBoost
  - LGBM

# XGBoost settings
enable_categorical: false
XGB:
  num_boost_round: 100
  early_stopping_rounds: 10
  verbose_eval: 20
  enable_categorical: false
  use_label_encoder: false

# LGBM settings
LGBM:
  num_boost_round: 100
  early_stopping: 10
  log_evaluation: 20

# SHAP settings
max_shap_interaction_memory_gb: 256.0
calculate_shap_interactions: false

# cross validation type
cross_validation_type: TimeSeriesSplit
#cross_validation_type: StratifiedKFold

# number of cross validation splits
n_splits: 5

# hyperparameters 
use_best_params: true
tune_hyperparameters: false

# chart options
feature_importance_chart: true
shap_summary_plot: true
shap_force_plot: true
shap_dependence_plot: true

