# Common model settings
experiment_name: "NBA Predictor"
experiment_description: "NBA Predictor"

# Data sorting
sort_columns:
  - season
  - season_progress
sort_order:
  - true
  - true

# Feature settings
categorical_features:
  - h_team_id
  - v_team_id

non_useful_columns: []
primary_id_column: game_id

# Cross validation settings
cross_validation_type: TimeSeriesSplit
n_splits: 5
random_state: 42

# Analysis settings
generate_learning_curve_data: true
calculate_shap_values: true
max_shap_interaction_memory_gb: 256.0
calculate_shap_interactions: false

# Chart options
chart_options:
  confusion_matrix: true
  roc_curve: true
  feature_importance:
    enabled: true
    n_features: 25
  shap_summary:
    enabled: true
    n_features: 25
  shap_beeswarm:
    enabled: true
    n_features: 25
  learning_curve: true 