# Optuna optimization settings
optuna:
  n_trials: 20
  scoring: auc
  direction: maximize
  pruner: 'median'  # Available: 'median', 'hyperband', 'threshold'
  n_startup_trials: 10
  n_warmup_steps: 5
  interval_steps: 1

# XGBoost parameter space
xgboost:
  static_params:
    verbosity: 0
    random_state: 42
    objective: binary:logistic
    eval_metric: auc
    tree_method: hist

  dynamic_params:
    num_round: [2, 1000, int]
    learning_rate: [1.0e-3, 1.0, float, true]  # true for log scale
    max_bin: [2, 1000, int]
    max_depth: [1, 8, int]
    alpha: [1.0e-16, 12, float, true]
    gamma: [1.0e-16, 12, float, true]
    reg_lambda: [1.0e-16, 12, float, true]
    colsample_bytree: [1.0e-16, 1.0, float, true]
    subsample: [1.0e-16, 1.0, float, true]
    min_child_weight: [1.0e-16, 12, float, true]
    scale_pos_weight: [1, 15, int]

# LightGBM parameter space
lightgbm:
  static_params:
    objective: binary
    metric: auc
    verbosity: -1

  dynamic_params:
    num_leaves: [2, 256, int]
    learning_rate: [1.0e-3, 1.0, float, true]
    feature_fraction: [0.1, 1.0, float]
    bagging_fraction: [0.1, 1.0, float]
    min_child_samples: [1, 100, int]
