# Optuna optimization settings
optuna:
  n_trials: 100
  scoring: 'auc'  # Supported metrics: 'accuracy', 'auc', 'f1'
  direction: 'maximize'
  pruner: 'median'  # Available: 'median', 'hyperband', 'threshold'
  n_startup_trials: 10
  n_warmup_steps: 5
  interval_steps: 1

# XGBoost parameter space
xgb_param_space:
  num_round: !suggest_int
    name: num_round
    low: 2
    high: 1000
  learning_rate: !suggest_float
    name: learning_rate
    low: 1.0e-3
    high: 1.0
  max_bin: !suggest_int
    name: max_bin
    low: 2
    high: 1000
  max_depth: !suggest_int
    name: max_depth
    low: 1
    high: 8
  alpha: !suggest_float
    name: alpha
    low: 1.0e-16
    high: 12.0
  gamma: !suggest_float
    name: gamma
    low: 1.0e-16
    high: 12.0
  reg_lambda: !suggest_float
    name: reg_lambda
    low: 1.0e-16
    high: 12.0
  colsample_bytree: !suggest_float
    name: colsample_bytree
    low: 1.0e-16
    high: 1.0
  subsample: !suggest_float
    name: subsample
    low: 1.0e-16
    high: 1.0
  min_child_weight: !suggest_float
    name: min_child_weight
    low: 1.0e-16
    high: 12.0
  scale_pos_weight: !suggest_int
    name: scale_pos_weight
    low: 1
    high: 15

# LightGBM parameter space
lgbm_param_space:
  num_leaves: !suggest_int
    name: num_leaves
    low: 2
    high: 256
  learning_rate: !suggest_float
    name: learning_rate
    low: 1.0e-3
    high: 1.0
  max_depth: !suggest_int
    name: max_depth
    low: 1
    high: 8
  min_child_samples: !suggest_int
    name: min_child_samples
    low: 1
    high: 100
  subsample: !suggest_float
    name: subsample
    low: 0.1
    high: 1.0
  colsample_bytree: !suggest_float
    name: colsample_bytree
    low: 0.1
    high: 1.0
  reg_alpha: !suggest_float
    name: reg_alpha
    low: 1.0e-16
    high: 12.0
  reg_lambda: !suggest_float
    name: reg_lambda
    low: 1.0e-16
    high: 12.0
