# Default preprocessing settings

# Scaling Options:
# - standard: StandardScaler
# - minmax: MinMaxScaler
# - maxabs: MaxAbsScaler
# - robust: RobustScaler
# - null: No scaling

# Handling Missing - numerical Values Options:
# - mean: Replace missing values with the mean of the feature
# - median: Replace missing values with the median of the feature
# - mode: Replace missing values with the mode of the feature
# - null: Leave missing values as they are

# Handling Missing - categorical Values Options:
# - constant: Replace missing values with a constant value
# - null: Leave missing values as they are

# Handling Outliers Options:
# - winsorize: Winsorize outliers
# - clip: Clip outliers
# - null: Leave outliers as they are

# Categorical Encoding Options:
# - ordinal: Ordinal encoding
# - target: Target encoding
# - frequency: Frequency encoding
# - null: Leave categorical variables as they are



preprocessing:
  default:
    numerical:
      scaling: standard
      handling_missing: mean
      handling_outliers: null

    categorical:
      handling_missing: constant
      max_categories: null
      min_frequency: null


  # Model-specific preprocessing settings
  model_specific:
    LogisticRegression:
      numerical:
        scaling: standard
        handling_missing: mean
        handling_outliers: winsorize
      categorical:
        handling_missing: constant


    RandomForest:
      numerical:
        scaling: null
        handling_missing: mean
        handling_outliers: null
      categorical:
        encoding: ordinal
        handling_missing: null
    
    XGBoost:
      numerical:
        scaling: null  
        handling_missing: null
      categorical:
        encoding: ordinal
        handling_missing: null

    LGBM:
      numerical:
        scaling: null  
        handling_missing: null
      categorical:
        encoding: label
        handling_missing: null
    
    NeuralNetwork:
      numerical:
        scaling: standard
        handling_missing: mean
        handling_outliers: clip
      categorical:
        encoding: null
        handling_missing: constant
